version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
#    mem_limit: "200m"
#    mem_reservation: "50m"
#    cpus: "0.1"
#    cpuset: "2"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 200M
        reservations:
          cpus: '0.1'
          memory: 50M
    restart: always
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
    networks:
      - mysql-compose-network

  app:
    build: .
#    mem_limit: "150m"
#    mem_reservation: "50m"
#    cpus: "1"
#    cpuset: "2"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 200M
        reservations:
          cpus: '0.1'
          memory: 20M
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    depends_on:
      - mysqldb
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "create-drop"
        }'
    stdin_open: true
    tty: true
    networks:
      - mysql-compose-network

volumes:
  db:
  
networks:
  mysql-compose-network:
    driver: bridge
    
